tasks:
  - command: |
      sudo apt-get update
      sudo apt-get --fix-missing install libleptonica-dev libtesseract-dev tesseract-ocr-all libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl-dev -y
      pip3 install opencv-python pytesseract matplotlib==3.2.2 numpy==1.18.5 ocrd-fork-pylsd==0.0.3 opencv-python==4.2.0.34 scipy==1.5.0 imutils rembg